### ISSUE TITLE
Implement Centralized Configuration System

### ISSUE THREAD

**Issue by ojasaklechat41** [ojasaklechat41/oju#5]
# Implement Centralized Configuration System

## Description
Create a unified configuration system to manage application settings and runtime parameters from multiple sources, with a strong focus on security and user-provided credentials.

## Basic Usage
```python
from oju.agent import Agent

# Basic initialization with minimal parameters
agent = Agent("weather_agent")  # Loads configuration automatically
response = agent("What's the weather like today?")
print(response)
```

## Advanced Usage
```python
from oju.agent import Agent
from oju.config import load_config

# Load configuration from a specific file
config = load_config("config/production.yaml")

# Initialize agent with explicit configuration
agent = Agent(
    "research_agent",
    config=config.agents.research,
    # Runtime overrides take precedence
    temperature=0.8,
    max_tokens=2000
)

# Use environment variables for sensitive data
import os
os.environ["OPENAI_API_KEY"] = "your-api-key"

# Environment-specific configuration
if os.getenv("ENV") == "production":
    agent = Agent("production_agent", config=config.production.agents.default)
else:
    agent = Agent("dev_agent", config=config.development.agents.default)

# Nested configuration with overrides
agent = Agent("custom_agent", **{
    "model": "gpt-4-turbo",
    "provider": "openai",
    "api_key": os.getenv("OPENAI_API_KEY"),
    "generation": {
        "temperature": 0.7,
        "max_tokens": 1000
    }
})
```

## Key Principles
- **No Built-in API Keys**: The library will never include or hardcode any API keys
- **User-Provided Credentials**: All API keys and sensitive data must be provided by the user
- **Secure Handling**: Ensure secure storage and handling of user-provided credentials
- **Environment-Aware**: Support different configurations for development, testing, and production

## Integration with Agent()
The configuration system will enhance the `Agent` class in several key ways:

1. **Simplified Initialization**:
   ```python
   # Before (manual configuration)
   agent = Agent(
       agent_name="my_agent",
       model="gpt-4",
       provider="openai",
       api_key=os.getenv("OPENAI_API_KEY"),
       temperature=0.7,
       max_tokens=1000
   )
   
   # After (using centralized config)
   agent = Agent("my_agent")  # Automatically loads config
   ```

2. **Secure API Key Management**:
   ```yaml
   # config.yaml
   agents:
     my_agent:
       provider: openai
       model: gpt-4
       # api_key loaded from environment variable
       api_key: ${OPENAI_API_KEY}
   ```

3. **Environment-Specific Settings**:
   ```yaml
   # config.dev.yaml
   agents:
     my_agent:
       provider: openai
       model: gpt-3.5-turbo  # Cheaper for development
   
   # config.prod.yaml  
   agents:
     my_agent:
       provider: openai
       model: gpt-4  # More capable for production
   ```

4. **Runtime Overrides**:
   ```python
   # Start with configured settings
   agent = Agent("my_agent")
   
   # Override specific settings at runtime
   agent.update_config({
       "temperature": 0.9,
       "max_tokens": 500
   })
   ```

## Configuration Sources (in order of precedence):
1. Runtime parameters (passed directly to Agent())
2. Environment variables (with OJU_ prefix)
3. Configuration files (YAML/JSON/TOML)
4. Default values (built into the library)

## Security Considerations
- Never log or expose API keys
- Support for secret management services (AWS Secrets Manager, HashiCorp Vault)
- Environment variable interpolation for sensitive values
- Config validation with Pydantic

## Implementation Plan
1. Create Config class to handle loading and merging configurations
2. Add support for multiple file formats (YAML, JSON, TOML)
3. Implement environment variable interpolation
4. Add configuration validation
5. Update Agent class to use new configuration system
6. Add documentation and examples

## Dependencies
- PyYAML for YAML support
- python-dotenv for .env file support
- pydantic for data validation
- Optional: toml for TOML support

## Testing
- Unit tests for configuration loading and merging
- Integration tests with environment variables
- Security tests for sensitive data handling
- Performance tests for configuration loading
